-- Expand RequestingTeam enum with new team values
ALTER TYPE "RequestingTeam" ADD VALUE IF NOT EXISTS 'MANAGEMENT';
ALTER TYPE "RequestingTeam" ADD VALUE IF NOT EXISTS 'ADMIN_TEAM';
ALTER TYPE "RequestingTeam" ADD VALUE IF NOT EXISTS 'BUSINESS_UM';
ALTER TYPE "RequestingTeam" ADD VALUE IF NOT EXISTS 'BUSINESS_AZURO';
ALTER TYPE "RequestingTeam" ADD VALUE IF NOT EXISTS 'BUSINESS_PROPVR';
ALTER TYPE "RequestingTeam" ADD VALUE IF NOT EXISTS 'BUSINESS_IPM';
ALTER TYPE "RequestingTeam" ADD VALUE IF NOT EXISTS 'BUSINESS_NRI';
ALTER TYPE "RequestingTeam" ADD VALUE IF NOT EXISTS 'BUSINESS_INDIA_SALES';
ALTER TYPE "RequestingTeam" ADD VALUE IF NOT EXISTS 'PERFORMANCE_MARKETING';
ALTER TYPE "RequestingTeam" ADD VALUE IF NOT EXISTS 'TECH';
ALTER TYPE "RequestingTeam" ADD VALUE IF NOT EXISTS 'CONTENT';
ALTER TYPE "RequestingTeam" ADD VALUE IF NOT EXISTS 'SEO';

-- Add requesterName and subTeam to design_requests
ALTER TABLE "design_requests"
  ADD COLUMN IF NOT EXISTS "requesterName" TEXT,
  ADD COLUMN IF NOT EXISTS "subTeam"       TEXT;
